targets:
  $default:
    builders:
      cloud_firestore_odm_generator:
        enabled: true
        generate_for:
          include:
            - lib/*
            - lib/**
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/*
            - lib/**
        options:
          create_field_map: true
          create_per_field_to_json: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - 'type=lint'
