name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0
  google_sign_in_dartio: ^0.2.2+1 # For Windows support

dev_dependencies:
  http: ^0.13.3

flutter:
  uses-material-design: true
