name: firebase_crashlytics_example
description: Demonstrates how to use the firebase_crashlytics plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
